# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://biswesh456.github.io/
baseurl: /
title: Biswesh Mohapatra
author: Biswesh Mohapatra
description: Personal blog and resume
avatar: profile.png
email: biswesh123@gmail.com
github: biswesh456 # username
twitter: bis1602
linkedin: biswesh-mohapatra-199158120
crossvalidated: users/253773/biswesh-mohapatra   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
